### ISSUE TITLE
web browser cannot establish secure connection.

### ISSUE THREAD

**Issue by gdlesage** [earlephilhower/psychoplug#8]
installed your firmware on a "eco plug"  switch  which has a esp8266 with complete success until the last step.   After successful uploading by arduino 1.8.5, I tried to get configuration web page to load.  I was able to see initial page with " go to configuration", but when that was clicked, the browser asked for secure page at 192.168.4.1, but I got error that said invalid ssl response.   I have tried chrome, IE, and cellphone with a variety of browsers, all with the same results.   I followed you instructions exactly, including the modification with pull 3001 and I got no errors in the arduino IDE upload. I have flashed the firmware twice with the same results.  I am at a loss what to do next.

**Comment by earlephilhower** [comment]
Howdy,

My original PR was in Feb this year, IIRC, but there have recently been major changes in the IP stack in the main github branch which might have either killed SSL or are up so much memory it can't function in the app.

I hate to ask this, but I'm not going to be able to run it myself for a bit due to family duties:  could you verify, either on your EcoPlug or any ESP8266, that w/the latest GIT the simple examples work properly?  If not, then there's no need for you to bother with anything else until I get w/ d-a-v and others on fixing whatever they broke.

If it does work, that most likely means a memory issue has cropped up.  Can you run it with logging (don't plug into the wall, just power it up thru serial and connect via WIFI while it's on your workbench) and capture the heap free logs?  I believe I dump a ESP.getHeapFree() every few cycles of the main loop, and if it comes up too small then SSL will crash due to OOM errors in the AXTLS library.

Thx
-EFP3

**Comment by gdlesage** [comment]
Thanks for the info-
Could not get nc to work on serial port, but did get putty to work and the output from putty is the following output, each line about every 5 seconds.  
000000: @115023: ESP Heap Free=39080
000000: @120024: ESP Heap Free=39080
000000: @125025: ESP Heap Free=39080
000000: @130026: ESP Heap Free=39080
000000: @135027: ESP Heap Free=39080
000000: @140028: ESP Heap Free=39080
000000: @145029: ESP Heap Free=38768
000000: @150030: ESP Heap Free=39080

the above suggest to me that there is memory available  
I am not sure what you mean by GIT simple examples
I have recently uploaded firmwares to several NodeMCUs to work with my smartthings hub and they work fine and no problems uploading firmware.

later 
when I try to load webpage I get the following on serial output:
000000: -WebReadRequest: Timeout @ 2778608
000000: -HTTPS setup request
000000: @2778615: ESP Heap Free=38608
000000: +HTTPS setup request

**Comment by gdlesage** [comment]
I started from scratch and ran through everything again.   Now I get  different SSL error at a attempted web browser connection to psychoplug using google chrome:
NET::ERR_CERT_INVALID
Subject: 127.0.0.1
Issuer: 127.0.0.1
Expires on: Jul 22, 2031
Current date: Nov 12, 2017
PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIBQzCB7gIJAOp7iF2KDURHMA0GCSqGSIb3DQEBCwUAMCkxEzARBgNVBAoMCnBz
eWNob3BsdWcxEjAQBgNVBAMMCTEyNy4wLjAuMTAeFw0xNzExMTIxNTI5MTRaFw0z
MTA3MjIxNTI5MTRaMCkxEzARBgNVBAoMCnBzeWNob3BsdWcxEjAQBgNVBAMMCTEy
Ny4wLjAuMTBcMA0GCSqGSIb3DQEBAQUAA0sAMEgCQQD4Cak/JxpnwSP2BC2/0OIE
2BxiJ3V2bEs8sc+rpeY4tRK1BgstulXfU5OCBe/VBuB0b+NpxUecwepXnSO044v1
AgMBAAEwDQYJKoZIhvcNAQELBQADQQCwaJSh6ixPRvGdLzomJUXfcomU3UY1Lom8
SQH4/+PuwcxzcJNIoKd8teCj2F6cCjv8kzc/npgp7ruGCm1r/TOI
-----END CERTIFICATE-----
 
I have generated key.h and x509.h several times, with either 512 or 1024 bit length with the same results.
OpenSSL is the latest:  OpenSSL> OpenSSL 1.1.0g  2 Nov 2017.  Keys were generated both before and after  complete upgrade and sync of arch linux with same results.

the following is output with running "make-certs-256.sh", with no errors

beginning
/tmp /media/usb/share/downloads/tmp
Generating RSA private key, 1024 bit long modulus
......................................................................++++++
............++++++
e is 65537 (0x010001)
Generating RSA private key, 1024 bit long modulus
........................................++++++
............++++++
e is 65537 (0x010001)
writing RSA key
Signature ok
subject=O = psychoplug, CN = 127.0.0.1
Getting Private key
Signature ok
subject=O = psychoplug, CN = 127.0.0.1
Getting CA Private Key
/media/usb/share/downloads/tmp
end

I can access the web set page by using chrome on cellphone, it has an option to ignore ssl errors and I have set up switch for time, auto off/on and mqtt triggering and all that works fine.   

I am unable to tell if I am generating invalid keys or the ssl is broke in the firmware.

**Comment by earlephilhower** [comment]
Can you try the example, File->Examples->ESP8266Wifi->WiFiHTTPSServer ?

That's a basic HTTPS server using a prebuilt key.  Upload it and go to https://<ip>/gpio/0 (or /gpio/1) to toggle a GPIO pin.  Chrome/Google will complain about it being an untrusted (i.e. self-signed) cert, but you can hit Advanced and actually continue.

I just tried that against the head + pull/3001 and it ran fine for me.  
![image](https://user-images.githubusercontent.com/11875/32751460-d8bd24e6-c87a-11e7-8737-c3b91aeef87f.png)
(the redlined https means simply that it's an untrusted cert auth.)

If the demo doesn't work, you've got some web browser issue to work around.  Chrome and Firefox both will complain since it's an untrusted authority, but that's a simple fix for you.

Can you rerun with a 512b key?  1024b keys take >2x the RAM (and it's much more than 1024 bits) to work with inside the ESP8266 and don't leave much memory for anything at all.  I'm running my own setup with 512b keys.

**Comment by gdlesage** [comment]
thanks for the help

I installed the WiFiHTTPSServer on the ecoplug and it gives identical as your results above, with message GPIO low or high with the url gpio/0 or gpio/1, respectively.  But WiFiHTTPSServer works only chrome in cellphone  or chrome in a chromebook and not  with windows chrome or IE.  In either cellphone and chromebook I have to choose to ignore SSL errors which windows chrome does not allow me to do.  Seeing that the WiFiHTTPSServer example behaves identically to psychoplug, the problem is  due to browsers and not the firmware.  I will just use the chromebook to set them up.

One additional problem, for MQTT, I have the topics published working by setting MQTT on, the host set to the IP address of my broker, port 1883 and topic set to "plug"
Using mosquitto I can successfully  subscribe to "powerstate"  by:
mosquitto_sub -t "plug/powerstate"

when I manually or schedule turn switch off or on, or I get 0 and 1 respectively from mosquitto_sub.  There is no MQTT response when I use CGI control of the switch.  

But I am unable to get MQTT subscribed to work.  When I send the command:
mosquitto_pub -t "plug/remotepower" -m '1'
I expect the switch to turn on but nothing happens.  There are no messages in the UDP log.  
I am likely missing something simple to make MQTT commands to the switch, perhaps you can give me a clue.

**Comment by earlephilhower** [comment]
Ah, good catch.  That's actually by design of the AXTLS setup.  There's only 1 set of SSL buffers available, not 1 per connection, so when a web request comes in the MQTT has to stop or you end up killing them both when they try and overwrite each other in the TCP stack.  So on receipt of a web request we StopMQTT()...and the relay control tries to do the report (unsuccessfully, since MQTT's not running during the request processing) .

It's possible to note this and send the MQTT message after the request processing is completed.

Could you close this bug and open a new one to that effect so it can be tracked?  It's not complicated, but it's probably going to be a bit before I can get back to it.

**Comment by earlephilhower** [comment]
Oh, and for IE you can probably import the self-signed certificate to the Windows certstore to make it trusted.  certmgr.msc is probably your friend there, but I've never tried since I only use Firefox or Chrome.

**Comment by gdlesage** [comment]
I will just use the chromebook, which my understanding is linux chrome, it works fine, with the  ignore ssl option.  I will open a new issue on MQTT.  thanks
