### ISSUE TITLE
mqtt switch  command

### ISSUE THREAD

**Issue by gdlesage** [earlephilhower/psychoplug#9]
I am unable to get MQTT subscribed to work. When I send the command:
mosquitto_pub -t "plug/remotepower" -m '1'

I expect the switch to turn on but nothing happens. 
In options, i have  MQTT on, the host set to the IP address of my broker, port 1883 and topic set to "plug"

I can successfully subscribe to "powerstate" by:
mosquitto_sub -t "plug/powerstate"

When I manually or schedule a turn switch off or on, or I get 0 and 1 respectively from mosquitto_sub. There is no MQTT response when I use CGI control of the switch.

I am likely missing something simple to make MQTT commands to turn the  switch off or on, perhaps you can give me a clue.

**Comment by gdlesage** [comment]
bump anyone get mqtt to turn on/off switch?

**Comment by earlephilhower** [comment]
Sorry, I've been quite busy with other things.  I am sure at one point it was working, but right now my 4 switches are not MQTT connected, just on their own internal timer, and were using the SDK/libs from when they were built about a year ago.  It's possible something's changed breaking the MQTT input connection.  The code is isolated in mqtt.cpp, so you should be able to add in some debugging prints() and trace this if you're really in a hurry.

**Comment by bradc87** [comment]
I am also having this issue, subscriptions are no problem, and I can see mosquitto publishing to the device, but the device is not responding to the mqtt publishes.

**Comment by bradc87** [comment]
In addition to this issue, the status.html page is no longer working. 

curl -k https://192.168.0.102/status.html
curl: (52) Empty reply from server

That said, thank you so much for providing such a great piece of software, I have flashed 4 ecoplugs with this and i look forward to building my home automation system around it.

**Comment by earlephilhower** [comment]
Are you using SSL connected MQTT or unencrypted MQTT?  There were some changes in the SSL codebase at 2.4.0 to enable true bidirectional comms over SSL (using a single, unidirectional buffer...its quite a cool hack) which may be related to this if you're doing SSL.  Try the latest git head in that case, as 2.4.*0* had a few WiFi issues.

Otherwise, the entire MQTT processing is handled in mqtt.cpp.  It's very simple and just calls the MQTT lib's subscribe on <mqttname>/remotepower and looks for "1" or "0" (string, not binary integer).  Could you instrument the code w/some printfs and see if it's even getting that callback?  If not, maybe there's an MQTT lib issue because the code setting it up is trivial:
````
  snprintf_P(topic, sizeof(topic), PSTR("%s/remotepower"), settings.mqttTopic);
  mqttClient.subscribe(topic);
````
If it is getting the callback, you'll see it via the LogPrintf() that's there, or you can dump it yourself for further inspection.

**Comment by bradc87** [comment]
I am using unencrypted. Im not very comfortable with the code side of
things, but if you could give me some instructions on how to OTA some new
code to the device, im happy to help.

- Brad

**Comment by gszakacs** [comment]
Ok. Got MQTT working good now.

![image](https://user-images.githubusercontent.com/10700953/42187745-1e7e12a6-7e1f-11e8-8acb-c7084e5c0541.png)

![image](https://user-images.githubusercontent.com/10700953/42187769-37f2e64e-7e1f-11e8-99d2-2db0fdcdec4b.png)

**Comment by earlephilhower** [comment]
Great!  Would you like to make a PR?

**Comment by gszakacs** [comment]
I am new to making suggestions on github and not sue what PR is. If it is some kind of release, before you/I do that, you could take a 5-10 minute look at the power.cpp file and see if you are experiencing the noisy readings because of reading 12 bytes instead of 16 ? I do not understand much of how the "wire" readout is working, but I do see that you are reading 12 bytes packets instead of 16. I was wondering if that could be the issue. Thanks

**Comment by earlephilhower** [comment]
Not a problem, I can do the 1-liner simply enough.  "PR" = "Pull Request".  Basically you fork someone's repo, clone your forked version to your PC, make a patch branch, do your changes, commit and push back to your private GIT copy.  Then the GitHub web interface can be used to send in a pull request which the original repo can merge.  That preserves who did the change (i.e. it would show "@gszakacs" in the "git blame" on my repo).  It's simpler than it sounds.

For the power, you could be right.  Presently I've `#if 0`'d the whole block as I was not able to get repeatable measurements.  I didn't spend too much time on it as my own use is more for the timing functionality (fish tank lights, landscape lights, xmas lights, etc.) and not for monitoring.  I think I spent a morning trying different wattage lightbulbs and reading out the returned values and ended up with garbage but still threw it into LibreOffice to do a linear regression to figure out the transfer function.  It didn't work well at all.

Wire is a pretty simple I2C software implementation, so changing "12" to "16" will make it try and shift in all 16 bytes.  I don't know if you need to *read out* those bytes in the app, though, but if you do then an add'l 4-bytes would need to be read in that loop.

**Comment by earlephilhower** [comment]
@gszakacs I've pushed a commit with your MQTT fix.  Could you please give it a go, quickly?  I can't seem to find my login to the free MQTT service I was using so can't connect myself.

Thx
-EFP3
